MVCTagHelper/Models/Medewerker.cs
namespace MVCTagHelper.Models
{
    public class Medewerker
    {
        public int MedewerkerId { get; set; }
        public int AfdelingId { get; set; }
        public string Naam { get; set; }
        public string Voornaam { get; set; }
        public string Email { get; set; }

        //foreign key reference
        public Afdeling? Afdeling { get; set; }

    }
}

MVCTagHelper/ViewModels/SearchResultsViewModel.cs
using MVCTagHelper.Models;

namespace MVCTagHelper.ViewModels
{
    public class SearchResultsViewModel
    {
        public IEnumerable<Medewerker>? Medewerkers { get; set; }
        public IEnumerable<AfdelingInfoViewModel>? AfdelingInfo { get; set; }

        public IEnumerable<Afdeling>? Afdelingen { get; set; }
        public IEnumerable<AfdelingLandViewModel>? AfdelingLandInfo { get; set; }

    }
}

MVCTagHelper/ViewModels/SearchViewModel.cs
namespace MVCTagHelper.ViewModels
{
    public class SearchViewModel
    {
        public string? SearchName { get; set; }
    }
}

MVCTagHelper/Controllers/AfdelingenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCTagHelper.Data;
using MVCTagHelper.Models;
using MVCTagHelper.ViewModels;

namespace MVCTagHelper.Controllers
{
    public class AfdelingenController : Controller
    {
        private readonly TagHelperDbContext _context;

        public AfdelingenController(TagHelperDbContext context)
        {
            _context = context;
        }

        // GET: Afdelingen
        public async Task<IActionResult> Index()
        {
            var tagHelperDbContext = _context.Afdelingen.Include(a => a.Locatie);
            return View(await tagHelperDbContext.ToListAsync());
        }

        // GET: Afdelingen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Afdelingen == null)
            {
                return NotFound();
            }

            var afdeling = await _context.Afdelingen
                .Include(a => a.Locatie)
                .ThenInclude(l => l.Land)
                .FirstOrDefaultAsync(m => m.AfdelingId == id);
            if (afdeling == null)
            {
                return NotFound();
            }

            return View(afdeling);
        }

        // GET: Afdelingen/Create
        public IActionResult Create()
        {
            ViewData["LocatieId"] = new SelectList(_context.Locaties, "LocatieId", "LocatieId");
            return View();
        }

        // POST: Afdelingen/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AfdelingId,AfdelingNaam,LocatieId")] Afdeling afdeling)
        {
            if (ModelState.IsValid)
            {
                _context.Add(afdeling);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocatieId"] = new SelectList(_context.Locaties, "LocatieId", "LocatieId", afdeling.LocatieId);
            return View(afdeling);
        }

        // GET: Afdelingen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Afdelingen == null)
            {
                return NotFound();
            }

            var afdeling = await _context.Afdelingen.FindAsync(id);
            if (afdeling == null)
            {
                return NotFound();
            }
            ViewData["LocatieId"] = new SelectList(_context.Locaties, "LocatieId", "LocatieId", afdeling.LocatieId);
            return View(afdeling);
        }

        // POST: Afdelingen/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AfdelingId,AfdelingNaam,LocatieId")] Afdeling afdeling)
        {
            if (id != afdeling.AfdelingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(afdeling);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AfdelingExists(afdeling.AfdelingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocatieId"] = new SelectList(_context.Locaties, "LocatieId", "LocatieId", afdeling.LocatieId);
            return View(afdeling);
        }

        // GET: Afdelingen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Afdelingen == null)
            {
                return NotFound();
            }

            var afdeling = await _context.Afdelingen
                .Include(a => a.Locatie)
                .FirstOrDefaultAsync(m => m.AfdelingId == id);
            if (afdeling == null)
            {
                return NotFound();
            }

            return View(afdeling);
        }

        // POST: Afdelingen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Afdelingen == null)
            {
                return Problem("Entity set 'TagHelperDbContext.Afdelingen'  is null.");
            }
            var afdeling = await _context.Afdelingen.FindAsync(id);
            if (afdeling != null)
            {
                _context.Afdelingen.Remove(afdeling);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult SearchFormAfdelingen()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SearchFormAfdelingen(SearchViewModel vm)
        {
            var afdeling = _context.Afdelingen
                .Include(a => a.Locatie)
                    .ThenInclude(l => l.Land)
                .Where(x => x.AfdelingNaam.Contains(vm.SearchName)).ToList();   
            if (afdeling.Count == 0)
            {
                  return View();
            }

            var results = new SearchResultsViewModel();
            results.Afdelingen = afdeling;
            results.AfdelingLandInfo = AfdelingLandViewModel(afdeling);
            return View("SearchResults", results);
        }

        private IEnumerable<AfdelingLandViewModel> AfdelingLandViewModel(IEnumerable<Afdeling> afd)
        {
            var info = afd.Select(x => new AfdelingLandViewModel()
            {
                AfdelingId = x.AfdelingId,
                AfdelingNaam = x.AfdelingNaam,
                Land = x.Locatie?.Land?.LandNaam
            });

            return info;

        }

        public IActionResult SearchResults(IEnumerable<Afdeling> afd)
        {
            var vm = new SearchResultsViewModel();
            vm.AfdelingLandInfo = (IEnumerable<AfdelingLandViewModel>?)afd;
            return View(vm);
        }


        private bool AfdelingExists(int id)
        {
          return _context.Afdelingen.Any(e => e.AfdelingId == id);
        }
    }
}

MVCTagHelper/Controllers/MedewerkersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCTagHelper.Data;
using MVCTagHelper.Models;
using MVCTagHelper.ViewModels;

namespace MVCTagHelper.Controllers
{
    public class MedewerkersController : Controller
    {
        private readonly TagHelperDbContext _context;

        public MedewerkersController(TagHelperDbContext context)
        {
            _context = context;
        }

        // GET: Medewerkers
        public async Task<IActionResult> Index()
        {
            var tagHelperDbContext = _context.Medewerkers.Include(m => m.Afdeling);
            return View(await tagHelperDbContext.ToListAsync());
        }

        // GET: Medewerkers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medewerker = await _context.Medewerkers
                .Include(m => m.Afdeling)
                .FirstOrDefaultAsync(m => m.MedewerkerId == id);
            if (medewerker == null)
            {
                return NotFound();
            }

            return View(medewerker);
        }

        // GET: Medewerkers/Create
        public IActionResult Create()
        {
            ViewData["AfdelingId"] = new SelectList(_context.Afdelingen, "AfdelingId", "AfdelingId");
            return View();
        }

        // POST: Medewerkers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MedewerkerId,AfdelingId,Naam,Voornaam,Email")] Medewerker medewerker)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medewerker);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AfdelingId"] = new SelectList(_context.Afdelingen, "AfdelingId", "AfdelingId", medewerker.AfdelingId);
            return View(medewerker);
        }

        // GET: Medewerkers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medewerker = await _context.Medewerkers.FindAsync(id);
            if (medewerker == null)
            {
                return NotFound();
            }
            ViewData["AfdelingId"] = new SelectList(_context.Afdelingen, "AfdelingId", "AfdelingId", medewerker.AfdelingId);
            return View(medewerker);
        }

        // POST: Medewerkers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MedewerkerId,AfdelingId,Naam,Voornaam,Email")] Medewerker medewerker)
        {
            if (id != medewerker.MedewerkerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medewerker);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedewerkerExists(medewerker.MedewerkerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AfdelingId"] = new SelectList(_context.Afdelingen, "AfdelingId", "AfdelingId", medewerker.AfdelingId);
            return View(medewerker);
        }

        // GET: Medewerkers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medewerker = await _context.Medewerkers
                .Include(m => m.Afdeling)
                .FirstOrDefaultAsync(m => m.MedewerkerId == id);
            if (medewerker == null)
            {
                return NotFound();
            }

            return View(medewerker);
        }

        // POST: Medewerkers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medewerker = await _context.Medewerkers.FindAsync(id);
            if (medewerker != null)
            {
                _context.Medewerkers.Remove(medewerker);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult SearchForm()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SearchForm(SearchViewModel vm)
        {
            //Na de post van ons formulier, open SearchResults.
            var medewerkers = _context.Medewerkers
                .Include(x => x.Afdeling)
                .Where(x => x.Naam.Contains(vm.SearchName) || x.Voornaam.Contains(vm.SearchName)).ToList();
            if (medewerkers.Count == 0)
            {
               return View();
            }

            var results = new SearchResultsViewModel();
            results.Medewerkers = medewerkers;
            results.AfdelingInfo = AfdelingInfoViewModel(medewerkers);


            return View("SearchResults", results);
        }

        private IEnumerable<AfdelingInfoViewModel> AfdelingInfoViewModel(IEnumerable<Medewerker> mws)
        {
            var info = mws.Select(x => new AfdelingInfoViewModel
            {
                AfdelingId = x.AfdelingId,
                AfdelingNaam = x.Afdeling.AfdelingNaam,
                MedewerkerNaam = $"{x.Voornaam} {x.Naam}"
            });

            return info;
        }
        public IActionResult SearchResults(IEnumerable<Medewerker> mws)
        {
            var vm = new SearchResultsViewModel();
            vm.Medewerkers = mws;
            return View(vm);
        }

        private bool MedewerkerExists(int id)
        {
            return _context.Medewerkers.Any(e => e.MedewerkerId == id);
        }


    }
}

MVCTagHelper/Views/Medewerkers/Create.cshtml
@model MVCTagHelper.Models.Medewerker

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Medewerker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AfdelingId" class="control-label"></label>
                <select asp-for="AfdelingId" class ="form-control" asp-items="ViewBag.AfdelingId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voornaam" class="control-label"></label>
                <input asp-for="Voornaam" class="form-control" />
                <span asp-validation-for="Voornaam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCTagHelper/Views/Medewerkers/Delete.cshtml
@model MVCTagHelper.Models.Medewerker

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medewerker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Voornaam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Voornaam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Afdeling)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Afdeling.AfdelingId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MedewerkerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCTagHelper/Views/Medewerkers/Details.cshtml
@using MVCTagHelper.ViewModels
@model MVCTagHelper.Models.Medewerker

@{
    ViewData["Title"] = "Details";
    var card = new MedewerkerCardViewModel();
    card.MedewerkerID = Model.MedewerkerId;
    card.AfdelingNaam = Model.Afdeling.AfdelingNaam;
    card.MedewerkerNaam = $"{Model.Voornaam} {Model.Naam}";
}

<h1>Details</h1>
<br />
<medewerker-card data="card" ></medewerker-card>
<br />

<div>
    <h4>Medewerker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Naam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Naam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Voornaam)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Voornaam)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Afdeling)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Afdeling.AfdelingId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.MedewerkerId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCTagHelper/Views/Medewerkers/Edit.cshtml
@model MVCTagHelper.Models.Medewerker

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Medewerker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MedewerkerId" />
            <div class="form-group">
                <label asp-for="AfdelingId" class="control-label"></label>
                <select asp-for="AfdelingId" class="form-control" asp-items="ViewBag.AfdelingId"></select>
                <span asp-validation-for="AfdelingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Naam" class="control-label"></label>
                <input asp-for="Naam" class="form-control" />
                <span asp-validation-for="Naam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Voornaam" class="control-label"></label>
                <input asp-for="Voornaam" class="form-control" />
                <span asp-validation-for="Voornaam" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCTagHelper/Views/Medewerkers/Index.cshtml
@model IEnumerable<MVCTagHelper.Models.Medewerker>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<br/>
<subtitle>Hier kan u een overzicht van de medewerkers vinden!</subtitle>
<br/>
<br/>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Naam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Voornaam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Afdeling)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Voornaam)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Afdeling.AfdelingId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.MedewerkerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MedewerkerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MedewerkerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVCTagHelper/Views/Medewerkers/SearchForm.cshtml
@using MVCTagHelper.ViewModels
@model SearchViewModel
<h4>Zoek een Medewerker op naam</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SearchForm">
            <div class="form-group">
                <label asp-for="SearchName" class="control-label"></label>
                <input asp-for="SearchName" class="form-control" />
            </div>
            <br />

            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

MVCTagHelper/Views/Medewerkers/SearchResults.cshtml
@using MVCTagHelper.ViewModels
@model SearchResultsViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Search results</h1>
<h2>Medewerkers</h2>

<hr />

<table class="table">
    <thead>
        <tr>
            <th>
                Naam
            </th>
            <th>
                Voornaam
            </th>
            <th>
                Email
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Medewerkers!)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Naam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Voornaam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>

                <td>
                    <a asp-action="Details" asp-route-id="@item.MedewerkerId">Details</a> 
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<h2>Afdeling info</h2>

<hr />

<table class="table">
    <thead>
        <tr>
            <th>
                Naam Afdeling
            </th>
            <th>
                Naam Medewerker
            </th>
            <th>
                Info
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.AfdelingInfo!)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AfdelingNaam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedewerkerNaam)
                </td>
                <td>
                    <a asp-action="Details" asp-controller="Afdelingen" asp-route-id="@item.AfdelingId">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>